# Generated by Django 4.2.4 on 2023-09-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_category', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
